### ISSUE TITLE
Localization changes not showing up on Dusk HD Version

### ISSUE THREAD

**Issue by TheUnstableNutcase** [NewBloodInteractive/dusk-localization#1]
If I go to steamapps\common\Dusk\Localization and edit Language_Default.txt, the edits that I make to the .txt file show up properly in the regular version of Dusk, but not if I launch Dusk HD. The changes that I made were specifically to the English text if that matters.

**Comment by 500pts** [comment]
Dusk HD has its own localization in its own folder, just need to move it to Dusk\DLC\Dusk HD\Localization instead
